### PR TITLE
1.21.1 Port help

### PR DESCRIPTION
**Pull request by sshcrack**
Hi, I've migrated most of the code to the 1.21.1!
Some things I've not been able to implement/fix yet:
- Winter music disc is missing (there was some new stuff with `JukeboxSongs`)
- Wolf offset when mounted to the sled is wrong (I think it has to do with the `Entity#getMyRidingOffset()` method being removed?)
- Buttons and other stuff seems to be removed on this branch for the config menu

### CODE REVIEW

**Comment by MehVahdJukaar** [comment]
Oh thanks, I've started to work on the port the other day, got a bit done but still missing 80 compile errors and I lost motivation. I planned on working on it this weekend. Thanks for the help. I'll pick it up and fix the remaining issues after I review your changes here

**Comment by MehVahdJukaar** [comment]
all looks good to me, Ill fix the rest soon. Only thing left after that wuld be to change all the data stuff, loot tables, c tags and such

**Comment by MehVahdJukaar** [comment]
dont have much time today. Would you mind testing it some? I fixed all the rest stuff +  allt he data stuff i could think of but im sure there is more stuff

**Comment by sshcrack** [comment]
yup will do today
edit: oops typo haha

**Pull request merged**
