### PR TITLE
Fix minor bugs

### PR DESCRIPTION
**Pull request by sshcrack**
Bugs fixed:
- Walk animation for Giant is too fast
- Snow Layers break when using a glow lights block on a leaf below
- Don't eat gingy when trying to make him sit

Tested:
I've tested Giants, Glow Lights (and using shears on them), Gingy and Sled

### CODE REVIEW

**Comment by MehVahdJukaar** [comment]
Hm where did that walk animation issue come from? They didn't do that in 1.20.

**Comment by MehVahdJukaar** [comment]
also i dont understand the glow light change. Why is it trying to clear a block entity where leaves are?

**Comment by MehVahdJukaar** [comment]
infact i cant even replicate the snow layer issue. To me just having set block and update does work ad does not break the snow layer

**Comment by MehVahdJukaar** [comment]
also the clearable change makes it so if a leaf block were to have an inventory for whatever reason, its content would be voided instead of dropped. also seems like thats not how it should work

**Comment by sshcrack** [comment]
Hm, I don't really know, didn't look at the 1.20 version specifically just
stuff that was weird in 1.21

**Comment by sshcrack** [comment]
> also the clearable change makes it so if a leaf block were to have an inventory for whatever reason, its content would be voided instead of dropped. also seems like thats not how it should work

Oh sorry then, didn't know that. Thought the block state would totally be copied to the mimic block

**Comment by sshcrack** [comment]
> infact i cant even replicate the snow layer issue. To me just having set block and update does work ad does not break the snow layer

Hm okay, because I had a snow layer on spruce leaves and it broke, will send a clip when I'm home

**Comment by sshcrack** [comment]
Okay, I'm trying some things to fix it
java_qqZYj7UxtV-ezgif com-resize

**Comment by sshcrack** [comment]
Aah, alright the important line of code seems to be:
```java
if (level instanceof ServerLevel sLevel) {
    sLevel.blockUpdated(pos, glowLight.getBlock());
}
```

Using `setBlockAndUpdate` instead of `setBlock` should be totally fine. Just the block of code above seems to be important.

**Comment by MehVahdJukaar** [comment]
the blockstate will be copied but not its block entity. most leaves blocks dont have a tile so while i could have that feature i dont thin its that necessary and dropping its content should be good enough.

I cant replicate the snow layer thing. Thing about level.setBlock with flag 3  (setBlockAndUpdate) is that it internally calls blockUpdated so those 2 likes there should be equivalent.

**Comment by MehVahdJukaar** [comment]
as for the gingerbread golem im trying to find out why its limb swing angle and speed is drastically incrased in 1.21. In 1.20 both were a lot slower

**Comment by sshcrack** [comment]
I think the local scale value that is the argument of function `setupRotations` is just straight up wrong. When using `this.scale` instead of scale, animations seem to be back at normal.
Will open up a PR

**Comment by sshcrack** [comment]
Okay the snow layer thing seems to be a weird runtime bug.
When using the Task runClient from Gradle, the snow layer issue is there.
But when running it directly via Intellij it just magically disappears. Don't really know why don't really know how but I guess it's solved then

**Comment by MehVahdJukaar** [comment]
i havent teted so i cant say if i can replicaate it outsie of d but makes no sense as to why it woul happen. if you look at leve.setBlock it literaly calls blockUpdated when flag has first bit as 1 so those 2 codes should be equivalent
image

For the giant entity i have no clue and debugging that stuff is so painful. scaling both angle and period by 0.1 seems to more or less get it how it was before but those numbers feel like they were pull put from thin air. i would like to see where they come from and why its dfferent from 1.20

**Comment by sshcrack** [comment]
I looked at wherre the value comes from:
grafik
With
grafik
And there is no scale attribute set for the giant. We can either leave it as is with `this.scale` or we *could* change the attribute / overwrite the method `getScale()`

**Pull request merged**
